# Generated by Django 2.0.2 on 2018-02-21 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 21, 16, 0, 0, 678466, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
