# Generated by Django 2.0.2 on 2018-03-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
